spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/g_paypay?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false&serverTimezone=Asia/Taipei
    username: root
    password: 1qaz@WSX
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      validation-timeout: 5000
      max-lifetime: 1800000

  profiles:
    active: elt-run
  main:
    web-application-type: none

mybatis:
  mapper-locations: classpath*:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    org.mybatis: DEBUG
    org.mybatis.spring: DEBUG
    com.example.ordermigratebatchmysql: INFO