spring:
  datasource:
    url: jdbc:mysql://192.168.1.171:3306/g_paypay?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false&serverTimezone=Asia/Taipei
    username: root
    password: 1qaz@WSX
#    url: jdbc:mysql://paydb.cluster-crdqz8lfsljk.ap-southeast-1.rds.amazonaws.com:3306/g_paypay?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false&serverTimezone=Asia/Taipei
#    username: admin
#    password: ZKhbpvmR970UsjHN&0
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      validation-timeout: 5000
      max-lifetime: 1800000
  main:
    web-application-type: none

mybatis:
  mapper-locations: classpath*:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    org.mybatis: DEBUG
    org.mybatis.spring: DEBUG
    com.example.ordermigratebatchmysql: INFO