spring:
  datasource:
    url: jdbc:mysql://192.168.1.213:3306/g_paypay?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false&serverTimezone=Asia/Taipei
    username: jyintadmin
    password: root17712nt11qaz@WSX
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      validation-timeout: 5000
      max-lifetime: 1800000

  config:
    activate:
      default: elt-run
  main:
    web-application-type: none

mybatis:
  mapper-locations: classpath*:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    org.mybatis: DEBUG
    org.mybatis.spring: DEBUG
    com.example.ordermigratebatchmysql: INFO

elt:
  enabled: false               # feature flag：可一鍵關閉
  batch-size: 150000
  max-batches-per-run: 50
  pause-ms: 300
  cron: "0 15 2 * * *"        # 每日 02:15 觸發（Asia/Taipei）
  zone-id: "Asia/Taipei"